#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'openssl'
cookbook 'postfix'

cookbook 'pingdom',
  :git => 'https://github.com/monigusto/chef-pingdom.git'

cookbook 'gdash',
  :git => 'https://github.com/monigusto/chef-gdash.git'

cookbook 'graphite_handler',
  :git => 'https://github.com/monigusto/chef-graphite_handler.git'

cookbook 'ntp',
  :git => 'git://github.com/opscode-cookbooks/ntp.git'

cookbook 'snmp',
   :git => 'https://github.com/monigusto/chef-snmp.git'

cookbook 'logstash',
   :git => 'https://github.com/monigusto/chef-logstash.git'

cookbook 'logstash_handler',
  :git => 'https://github.com/monigusto/logstash_handler.git'

cookbook 'graphite',
   :git =>  'https://github.com/monigusto/chef-graphite.git'

cookbook 'collectd',
   :git =>  'https://github.com/monigusto/chef-collectd.git'

cookbook 'jmxtrans',
   :git =>  'https://github.com/monigusto/chef-jmxtrans.git'

cookbook 'statsd',
   :git =>  'https://github.com/monigusto/chef-statsd.git'

# Cookbook from main community site is outdated
cookbook 'npm',
   :git =>  'https://github.com/monigusto/chef-npm.git'

cookbook 'solo-search',
   :git =>  'https://github.com/monigusto/chef-solo-search.git'

cookbook 'tasseo',
   :git => 'https://github.com/monigusto/chef-tasseo.git'

cookbook 'nagios',
   :git =>  'https://github.com/monigusto/chef-nagios.git'

cookbook 'collectd-carbon',
   :git =>  'https://github.com/monigusto/chef-collectd-carbon.git'

cookbook 'collectd-elasticsearch',
   :git =>  'https://github.com/monigusto/chef-collectd-elasticsearch.git'

cookbook 'nagios-check-graphite',
   :git =>  'https://github.com/monigusto/chef-nagios-check-graphite.git'

cookbook 'monigusto',
   :git =>  'https://github.com/monigusto/chef-monigusto.git'

# Needed for sensu , another one breaks
cookbook 'redis',
  :git => 'https://github.com/miah/chef-redis'

# Seems graphite chef-handler doesn't like the default runit
# Complains about finish_script
cookbook 'runit',
  :git => 'https://github.com/cookbooks/runit'

cookbook 'sensu-community-plugins',
  :git => 'https://github.com/monigusto/chef-sensu-community-plugins.git'

cookbook 'sensu',
  :git => 'https://github.com/monigusto/chef-sensu.git'
