#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'logstash',
   :git => 'https://github.com/jedi4ever/chef-logstash',
   :ref => 'flexible_config'

cookbook 'nagios',
   :git => 'https://github.com/jedi4ever/nagios',
   :ref => 'ubuntu-password-less-package'

cookbook 'graphite',
   :git =>  'https://github.com/jedi4ever/chef-graphite',
   :ref => 'more_config_options'

cookbook 'collectd',
   :git =>  'https://github.com/jedi4ever/chef-collectd',
   :ref => 'more_config_options'

cookbook 'jmxtrans',
   :git =>  'https://github.com/jedi4ever/chef-jmxtrans',
   :ref => 'minor_fixes'

cookbook 'statsd',
   :git =>  'https://github.com/jedi4ever/chef-statsd',
   :ref => 'statsd'

cookbook 'tasseo',
   :git =>  'git@github.com:jedi4ever/chef-tasseo.git',
   :ref => 'extra_configuration_options'

cookbook 'solo-search',
   :git =>  'git@github.com:jedi4ever/chef-solo-search.git',
   :ref => 'role_support'

# Examples

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
